version: "3.3"
services:
  database:
    image: "postgres:13"
    container_name: "localpg"
    environment:
      - POSTGRES_USER=pszk
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes: 
  postgres-volume:
    external: true